[project]
name = "hello-llm"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "lingamurty", email = "lingamurtych@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "dotenv>=0.9.9",
    "langchain>=1.4.0",
    "langchain-google-genai>=4.4.0",
    "langchain-openrouter>=0.2.8",
]

[project.scripts]
hello-llm = "hello_llm:main"

[build-system]
requires = ["uv_build>=0.12.6,<0.13.0"]
build-backend = "uv_build"
