[project]
name = "hello-langgraph"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "lingamurty", email = "lingamurtych@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "langchain>=1.4.0",
    "langchain-google-genai>=4.4.0",
    "langgraph>=1.2.11",
    "langgraph-cli[inmem]>=0.4.31",
    "python-dotenv>=1.2.3",
]

[project.scripts]
hello-langgraph = "hello_langgraph:main"

[build-system]
requires = ["uv_build>=0.12.6,<0.13.0"]
build-backend = "uv_build"
